INSERT INTO PUBLIC.EMPLOYEE
  (ID, FIRST_NAME, LAST_NAME, GENDER, DOB, SALARY, NICK_NAME, BEING_HIRED) VALUES
  (1, 'Geronimo', 'Alba', true, '1976-10-25', 25000.00, 'Gero', true);

INSERT INTO PUBLIC.EMPLOYEE
  (ID, FIRST_NAME, LAST_NAME, GENDER, DOB, SALARY, NICK_NAME, BEING_HIRED) VALUES
  (2, 'Banana', 'Split', true, '1976-11-20', 30000.00, 'Banana', true);
