CREATE TABLE DEPARTMENT
(
  ID   BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(200)                      NOT NULL,
);

INSERT INTO PUBLIC.DEPARTMENT (ID, NAME) VALUES (1, 'Not Assigned');
INSERT INTO PUBLIC.DEPARTMENT (ID, NAME) VALUES (2, 'Management');

ALTER TABLE PUBLIC.EMPLOYEE ADD DEPARTMENT_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE PUBLIC.EMPLOYEE ADD FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENT(ID);