CREATE TABLE TELEPHONE
(
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TEL_NUMBER  VARCHAR(200)                      NOT NULL,
  EMPLOYEE_ID BIGINT                            NOT NULL,
);

CREATE TABLE EMAIL
(
  ID            BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  EMAIL_ADDRESS VARCHAR(200)                      NOT NULL,
  EMPLOYEE_ID   BIGINT                            NOT NULL,
);


ALTER TABLE PUBLIC.TELEPHONE ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);
ALTER TABLE PUBLIC.EMAIL ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);

INSERT INTO PUBLIC.EMAIL (ID, EMAIL_ADDRESS, EMPLOYEE_ID) VALUES (1, 'banana@gmail.com', 2);
INSERT INTO PUBLIC.EMAIL (ID, EMAIL_ADDRESS, EMPLOYEE_ID) VALUES (2, 'banana@ccc.org', 2);
