CREATE TABLE TELEPHONE
(
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TEL_NUMBER  VARCHAR(20)                       NOT NULL,
  EMPLOYEE_ID BIGINT                            NOT NULL,
);

ALTER TABLE PUBLIC.TELEPHONE ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);

INSERT INTO PUBLIC.TELEPHONE (ID, TEL_NUMBER, EMPLOYEE_ID) VALUES (1, '0869999999', 2);
INSERT INTO PUBLIC.TELEPHONE (ID, TEL_NUMBER, EMPLOYEE_ID) VALUES (2, '0841111111', 2);