package com.chulabhornhospital.employee.mapper;

import com.chulabhornhospital.employee.domain.Email;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface EmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from PUBLIC.EMAIL",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into PUBLIC.EMAIL (ID, EMAIL_ADDRESS, ",
        "EMPLOYEE_ID)",
        "values (#{id,jdbcType=BIGINT}, #{emailAddress,jdbcType=VARCHAR}, ",
        "#{employeeId,jdbcType=BIGINT})"
    })
    int insert(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMAIL
     *
     * @mbggenerated
     */
    @InsertProvider(type=EmailSqlProvider.class, method="insertSelective")
    int insertSelective(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, EMAIL_ADDRESS, EMPLOYEE_ID",
        "from PUBLIC.EMAIL",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="EMAIL_ADDRESS", property="emailAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMPLOYEE_ID", property="employeeId", jdbcType=JdbcType.BIGINT)
    })
    Email selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMAIL
     *
     * @mbggenerated
     */
    @UpdateProvider(type=EmailSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMAIL
     *
     * @mbggenerated
     */
    @Update({
        "update PUBLIC.EMAIL",
        "set EMAIL_ADDRESS = #{emailAddress,jdbcType=VARCHAR},",
          "EMPLOYEE_ID = #{employeeId,jdbcType=BIGINT}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Email record);
}