package com.chulabhornhospital.employee.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.chulabhornhospital.employee.domain.Email;

public class EmailSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMAIL
     *
     * @mbggenerated
     */
    public String insertSelective(Email record) {
        BEGIN();
        INSERT_INTO("PUBLIC.EMAIL");
        
        if (record.getId() != null) {
            VALUES("ID", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getEmailAddress() != null) {
            VALUES("EMAIL_ADDRESS", "#{emailAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getEmployeeId() != null) {
            VALUES("EMPLOYEE_ID", "#{employeeId,jdbcType=BIGINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMAIL
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Email record) {
        BEGIN();
        UPDATE("PUBLIC.EMAIL");
        
        if (record.getEmailAddress() != null) {
            SET("EMAIL_ADDRESS = #{emailAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getEmployeeId() != null) {
            SET("EMPLOYEE_ID = #{employeeId,jdbcType=BIGINT}");
        }
        
        WHERE("ID = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}