package com.chulabhornhospital.employee.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.chulabhornhospital.employee.domain.Employee;

public class EmployeeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbggenerated
     */
    public String insertSelective(Employee record) {
        BEGIN();
        INSERT_INTO("PUBLIC.EMPLOYEE");
        
        if (record.getId() != null) {
            VALUES("ID", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getFirstName() != null) {
            VALUES("FIRST_NAME", "#{firstName,jdbcType=VARCHAR}");
        }
        
        if (record.getLastName() != null) {
            VALUES("LAST_NAME", "#{lastName,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            VALUES("GENDER", "#{gender,jdbcType=BOOLEAN}");
        }
        
        if (record.getDob() != null) {
            VALUES("DOB", "#{dob,jdbcType=DATE}");
        }
        
        if (record.getSalary() != null) {
            VALUES("SALARY", "#{salary,jdbcType=DECIMAL}");
        }
        
        if (record.getNickName() != null) {
            VALUES("NICK_NAME", "#{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getBeingHired() != null) {
            VALUES("BEING_HIRED", "#{beingHired,jdbcType=BOOLEAN}");
        }
        
        if (record.getDepartmentId() != null) {
            VALUES("DEPARTMENT_ID", "#{departmentId,jdbcType=BIGINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Employee record) {
        BEGIN();
        UPDATE("PUBLIC.EMPLOYEE");
        
        if (record.getFirstName() != null) {
            SET("FIRST_NAME = #{firstName,jdbcType=VARCHAR}");
        }
        
        if (record.getLastName() != null) {
            SET("LAST_NAME = #{lastName,jdbcType=VARCHAR}");
        }
        
        if (record.getGender() != null) {
            SET("GENDER = #{gender,jdbcType=BOOLEAN}");
        }
        
        if (record.getDob() != null) {
            SET("DOB = #{dob,jdbcType=DATE}");
        }
        
        if (record.getSalary() != null) {
            SET("SALARY = #{salary,jdbcType=DECIMAL}");
        }
        
        if (record.getNickName() != null) {
            SET("NICK_NAME = #{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getBeingHired() != null) {
            SET("BEING_HIRED = #{beingHired,jdbcType=BOOLEAN}");
        }
        
        if (record.getDepartmentId() != null) {
            SET("DEPARTMENT_ID = #{departmentId,jdbcType=BIGINT}");
        }
        
        WHERE("ID = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}