package com.chulabhornhospital.employee.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.chulabhornhospital.employee.domain.Telephone;

public class TelephoneSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TELEPHONE
     *
     * @mbggenerated
     */
    public String insertSelective(Telephone record) {
        BEGIN();
        INSERT_INTO("PUBLIC.TELEPHONE");
        
        if (record.getId() != null) {
            VALUES("ID", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getTelNumber() != null) {
            VALUES("TEL_NUMBER", "#{telNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getEmployeeId() != null) {
            VALUES("EMPLOYEE_ID", "#{employeeId,jdbcType=BIGINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TELEPHONE
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Telephone record) {
        BEGIN();
        UPDATE("PUBLIC.TELEPHONE");
        
        if (record.getTelNumber() != null) {
            SET("TEL_NUMBER = #{telNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getEmployeeId() != null) {
            SET("EMPLOYEE_ID = #{employeeId,jdbcType=BIGINT}");
        }
        
        WHERE("ID = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }
}