package com.chulabhornhospital.employee.mapper;

import com.chulabhornhospital.employee.domain.Telephone;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TelephoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TELEPHONE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from PUBLIC.TELEPHONE",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TELEPHONE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into PUBLIC.TELEPHONE (ID, TEL_NUMBER, ",
        "EMPLOYEE_ID)",
        "values (#{id,jdbcType=BIGINT}, #{telNumber,jdbcType=VARCHAR}, ",
        "#{employeeId,jdbcType=BIGINT})"
    })
    int insert(Telephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TELEPHONE
     *
     * @mbggenerated
     */
    @InsertProvider(type=TelephoneSqlProvider.class, method="insertSelective")
    int insertSelective(Telephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TELEPHONE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TEL_NUMBER, EMPLOYEE_ID",
        "from PUBLIC.TELEPHONE",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="TEL_NUMBER", property="telNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMPLOYEE_ID", property="employeeId", jdbcType=JdbcType.BIGINT)
    })
    Telephone selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TELEPHONE
     *
     * @mbggenerated
     */
    @UpdateProvider(type=TelephoneSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Telephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TELEPHONE
     *
     * @mbggenerated
     */
    @Update({
        "update PUBLIC.TELEPHONE",
        "set TEL_NUMBER = #{telNumber,jdbcType=VARCHAR},",
          "EMPLOYEE_ID = #{employeeId,jdbcType=BIGINT}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Telephone record);
}