package com.chulabhornhospital.employee.domain;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEPARTMENT.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEPARTMENT.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEPARTMENT.ID
     *
     * @return the value of PUBLIC.DEPARTMENT.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEPARTMENT.ID
     *
     * @param id the value for PUBLIC.DEPARTMENT.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEPARTMENT.NAME
     *
     * @return the value of PUBLIC.DEPARTMENT.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEPARTMENT.NAME
     *
     * @param name the value for PUBLIC.DEPARTMENT.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}