package com.chulabhornhospital.employee.domain;

public class Email {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMAIL.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMAIL.EMAIL_ADDRESS
     *
     * @mbggenerated
     */
    private String emailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMAIL.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private Long employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMAIL.ID
     *
     * @return the value of PUBLIC.EMAIL.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMAIL.ID
     *
     * @param id the value for PUBLIC.EMAIL.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMAIL.EMAIL_ADDRESS
     *
     * @return the value of PUBLIC.EMAIL.EMAIL_ADDRESS
     *
     * @mbggenerated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMAIL.EMAIL_ADDRESS
     *
     * @param emailAddress the value for PUBLIC.EMAIL.EMAIL_ADDRESS
     *
     * @mbggenerated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMAIL.EMPLOYEE_ID
     *
     * @return the value of PUBLIC.EMAIL.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMAIL.EMPLOYEE_ID
     *
     * @param employeeId the value for PUBLIC.EMAIL.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }
}