package com.chulabhornhospital.employee.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @mbggenerated
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @mbggenerated
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.GENDER
     *
     * @mbggenerated
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.DOB
     *
     * @mbggenerated
     */
    private Date dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.SALARY
     *
     * @mbggenerated
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.BEING_HIRED
     *
     * @mbggenerated
     */
    private Boolean beingHired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbggenerated
     */
    private Long departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @return the value of PUBLIC.EMPLOYEE.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @param id the value for PUBLIC.EMPLOYEE.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @mbggenerated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @param lastName the value for PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @mbggenerated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.GENDER
     *
     * @return the value of PUBLIC.EMPLOYEE.GENDER
     *
     * @mbggenerated
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.GENDER
     *
     * @param gender the value for PUBLIC.EMPLOYEE.GENDER
     *
     * @mbggenerated
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.DOB
     *
     * @return the value of PUBLIC.EMPLOYEE.DOB
     *
     * @mbggenerated
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.DOB
     *
     * @param dob the value for PUBLIC.EMPLOYEE.DOB
     *
     * @mbggenerated
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.SALARY
     *
     * @return the value of PUBLIC.EMPLOYEE.SALARY
     *
     * @mbggenerated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.SALARY
     *
     * @param salary the value for PUBLIC.EMPLOYEE.SALARY
     *
     * @mbggenerated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.NICK_NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.NICK_NAME
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.NICK_NAME
     *
     * @param nickName the value for PUBLIC.EMPLOYEE.NICK_NAME
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.BEING_HIRED
     *
     * @return the value of PUBLIC.EMPLOYEE.BEING_HIRED
     *
     * @mbggenerated
     */
    public Boolean getBeingHired() {
        return beingHired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.BEING_HIRED
     *
     * @param beingHired the value for PUBLIC.EMPLOYEE.BEING_HIRED
     *
     * @mbggenerated
     */
    public void setBeingHired(Boolean beingHired) {
        this.beingHired = beingHired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @return the value of PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbggenerated
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @param departmentId the value for PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbggenerated
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }
}