package com.chulabhornhospital.employee.domain;

public class Telephone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TELEPHONE.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TELEPHONE.TEL_NUMBER
     *
     * @mbggenerated
     */
    private String telNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TELEPHONE.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private Long employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TELEPHONE.ID
     *
     * @return the value of PUBLIC.TELEPHONE.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TELEPHONE.ID
     *
     * @param id the value for PUBLIC.TELEPHONE.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TELEPHONE.TEL_NUMBER
     *
     * @return the value of PUBLIC.TELEPHONE.TEL_NUMBER
     *
     * @mbggenerated
     */
    public String getTelNumber() {
        return telNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TELEPHONE.TEL_NUMBER
     *
     * @param telNumber the value for PUBLIC.TELEPHONE.TEL_NUMBER
     *
     * @mbggenerated
     */
    public void setTelNumber(String telNumber) {
        this.telNumber = telNumber == null ? null : telNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TELEPHONE.EMPLOYEE_ID
     *
     * @return the value of PUBLIC.TELEPHONE.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TELEPHONE.EMPLOYEE_ID
     *
     * @param employeeId the value for PUBLIC.TELEPHONE.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }
}